### ISSUE TITLE
Results of LLaMA-2 are different from Wanda

### ISSUE THREAD

**Issue by pprp** [VILA-Lab/GBLM-Pruner#1]
<img width="544" alt="image" src="https://github.com/VILA-Lab/GBLM-Pruner/assets/29230784/8c84f63d-4878-4fba-940a-5df974bbca09">

<img width="1123" alt="image" src="https://github.com/VILA-Lab/GBLM-Pruner/assets/29230784/828b90a7-43d0-451f-bc92-93be8ac6d82d">

For LLaMA-2, Wanda and GBLM-Pruner got different ppl. Any thought?

**Comment by RocktimJyotiDas** [comment]
Hi, thanks for the question. The numbers are different because, in the Wanda paper, they computed the perplexity for LLaMA-2 using a sequence length of 4096 from Wiki-Text, whereas in GBLM-Pruner, the sequence length is 2048.

**Comment by pprp** [comment]
Thank you for your answers. 😄
